name: nsisonglabs-quant-validator
version: 0.1.0.0
description: Trade validation system for Quant Research Platform
author: Isaac Emmanuel
maintainer: ei@nsisong.com
copyright: 2025
license: MIT

extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - cassava >= 0.5.2.0
  - bytestring >= 0.10.8.2
  - vector >= 0.12.0.1
  - time >= 1.8.0.2

executables:
  validator:
    main: Main.hs
    source-dirs: .
    ghc-options:
      - -Wall
      - -Werror
      - -O2
